[build]
  base = "app"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/xtream-api/*"
  to = "http://ctn34.xyz:8080/:splat"
  status = 200

[[redirects]]
  from = "/xtream/*"
  to = "http://dzcvip1.xyz:2095/:splat"
  status = 200

[[redirects]]
  from = "/xtream-fb/*"
  to = "http://ctn34.xyz:8080/:splat"
  status = 200

[[redirects]]
  from = "/p2095/*"
  to = "http://dzcvip1.xyz:2095/:splat"
  status = 200

[[redirects]]
  from = "/p8080/*"
  to = "http://dzcvip1.xyz:8080/:splat"
  status = 200

[[redirects]]
  from = "/tv8daion/*"
  to = "https://tv8.daioncdn.net/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
