import { createContext, useContext, useState, useEffect, type ReactNode } from 'react'

const data: Record<string, Record<string, string>> = {
  tr: {
    'nav.home': 'Ana Sayfa', 'nav.live': 'Canlı TV', 'nav.movies': 'Filmler', 'nav.series': 'Diziler',
    'nav.profile': 'Profil', 'nav.logout': 'Çıkış Yap', 'nav.search': 'Arama',
    'hero.play': 'İzle', 'hero.detail': 'Detay',
    'content.featured': 'Öne Çıkanlar', 'content.popular': 'Popüler', 'content.recent': 'Son Eklenenler',
    'content.similar': 'Benzer İçerikler', 'content.categories': 'Kategoriler', 'content.no_content': 'İçerik Bulunamadı',
    'content.seasons': 'Sezonlar', 'content.episodes': 'Bölümler', 'content.cast': 'Oyuncular',
    'content.director': 'Yönetmen', 'content.genre': 'Tür', 'content.release': 'Yıl', 'content.rating': 'Puan',
    'content.duration': 'Süre', 'content.trailer': 'Fragman',
    'player.play': 'Oynat', 'player.pause': 'Duraklat', 'player.buffering': 'Yükleniyor...',
    'player.mute': 'Sessiz', 'player.unmute': 'Sesi Aç', 'player.fullscreen': 'Tam Ekran',
    'player.settings': 'Ayarlar', 'player.speed': 'Hız', 'player.live': 'CANLI',
    'login.title': 'Giriş Yap', 'login.username': 'Kullanıcı Adı', 'login.password': 'Şifre',
    'login.button': 'Giriş Yap', 'login.error': 'Kullanıcı adı veya şifre hatalı',
    'login.loading': 'Giriş yapılıyor...', 'login.remember': 'Beni Hatırla',
    'avatar.title': 'Avatar Seç', 'avatar.button': 'Devam Et',
    'profile.subscription': 'Abonelik', 'profile.active': 'Aktif', 'profile.expired': 'Süresi Dolmuş',
    'profile.renew': 'Abonelik Yenile', 'profile.plans': 'Planlar', 'profile.server': 'Sunucu',
    'profile.status': 'Durum', 'profile.remaining': 'Kalan Süre', 'profile.unlimited': 'Sınırsız',
    'profile.live_status': 'Canlı TV', 'profile.open': 'Açık', 'profile.closed': 'Kapalı',
    'live.all': 'Tümü', 'live.search': 'Kanal Ara...', 'live.no_channels': 'Kanal bulunamadı',
    'common.loading': 'Yükleniyor...', 'common.error': 'Hata', 'common.retry': 'Tekrar Dene',
    'footer.rights': 'Tüm hakları saklıdır.',
    'premium.badge': 'Planınızı Seçin', 'premium.title': 'Fiyat Planları', 'premium.subtitle': 'Kendinize en uygun planı seçin',
    'premium.monthly': '1 Ay', 'premium.monthly.dur': '30 Gün', 'premium.quarterly': '3 Ay',
    'premium.quarterly.dur': '90 Gün', 'premium.yearly': '12 Ay', 'premium.yearly.dur': '365 Gün',
    'premium.buy': 'Satın Al', 'premium.popular': 'En Popüler',
    'premium.ultra': '4K Ultra HD', 'premium.world': 'Binlerce İçerik', 'premium.national': 'Yerli Yapımlar',
    'premium.sports': 'Yabancı Yapımlar', 'premium.vod': 'Güncel Arşiv',
  },
  en: {
    'nav.home': 'Home', 'nav.live': 'Live TV', 'nav.movies': 'Movies', 'nav.series': 'Series',
    'nav.profile': 'Profile', 'nav.logout': 'Logout', 'nav.search': 'Search',
    'hero.play': 'Play', 'hero.detail': 'Details',
    'content.featured': 'Featured', 'content.popular': 'Popular', 'content.recent': 'Recent',
    'content.similar': 'Similar', 'content.categories': 'Categories', 'content.no_content': 'No Content Found',
    'content.seasons': 'Seasons', 'content.episodes': 'Episodes', 'content.cast': 'Cast',
    'content.director': 'Director', 'content.genre': 'Genre', 'content.release': 'Year', 'content.rating': 'Rating',
    'content.duration': 'Duration', 'content.trailer': 'Trailer',
    'player.play': 'Play', 'player.pause': 'Pause', 'player.buffering': 'Loading...',
    'player.mute': 'Mute', 'player.unmute': 'Unmute', 'player.fullscreen': 'Fullscreen',
    'player.settings': 'Settings', 'player.speed': 'Speed', 'player.live': 'LIVE',
    'login.title': 'Login', 'login.username': 'Username', 'login.password': 'Password',
    'login.button': 'Sign In', 'login.error': 'Invalid username or password',
    'login.loading': 'Signing in...', 'login.remember': 'Remember Me',
    'avatar.title': 'Choose Avatar', 'avatar.button': 'Continue',
    'profile.subscription': 'Subscription', 'profile.active': 'Active', 'profile.expired': 'Expired',
    'profile.renew': 'Renew Subscription', 'profile.plans': 'Plans', 'profile.server': 'Server',
    'profile.status': 'Status', 'profile.remaining': 'Remaining', 'profile.unlimited': 'Unlimited',
    'profile.live_status': 'Live TV', 'profile.open': 'Open', 'profile.closed': 'Closed',
    'live.all': 'All', 'live.search': 'Search Channel...', 'live.no_channels': 'No channels found',
    'common.loading': 'Loading...', 'common.error': 'Error', 'common.retry': 'Retry',
    'footer.rights': 'All rights reserved.',
    'premium.badge': 'Choose Plan', 'premium.title': 'Pricing', 'premium.subtitle': 'Choose the best plan',
    'premium.monthly': '1 Month', 'premium.monthly.dur': '30 Days', 'premium.quarterly': '3 Months',
    'premium.quarterly.dur': '90 Days', 'premium.yearly': '12 Months', 'premium.yearly.dur': '365 Days',
    'premium.buy': 'Buy', 'premium.popular': 'Popular',
    'premium.ultra': '4K Ultra HD', 'premium.world': 'Thousands of Content', 'premium.national': 'Local Content',
    'premium.sports': 'Foreign Content', 'premium.vod': 'Updated Archive',
  },
  ru: {
    'nav.home': 'Главная', 'nav.live': 'ТВ', 'nav.movies': 'Фильмы', 'nav.series': 'Сериалы',
    'nav.profile': 'Профиль', 'nav.logout': 'Выйти', 'nav.search': 'Поиск',
    'hero.play': 'Смотреть', 'hero.detail': 'Детали',
    'content.featured': 'Рекомендуемое', 'content.popular': 'Популярное', 'content.recent': 'Новинки',
    'content.similar': 'Похожие', 'content.categories': 'Категории', 'content.no_content': 'Контент не найден',
    'content.seasons': 'Сезоны', 'content.episodes': 'Серии', 'content.cast': 'Актеры',
    'content.director': 'Режиссер', 'content.genre': 'Жанр', 'content.release': 'Год', 'content.rating': 'Рейтинг',
    'content.duration': 'Длительность', 'content.trailer': 'Трейлер',
    'player.play': 'Играть', 'player.pause': 'Пауза', 'player.buffering': 'Загрузка...',
    'player.mute': 'Без звука', 'player.unmute': 'Звук', 'player.fullscreen': 'На весь экран',
    'player.settings': 'Настройки', 'player.speed': 'Скорость', 'player.live': 'LIVE',
    'login.title': 'Вход', 'login.username': 'Имя', 'login.password': 'Пароль',
    'login.button': 'Войти', 'login.error': 'Неверное имя или пароль',
    'login.loading': 'Вход...', 'login.remember': 'Запомнить',
    'avatar.title': 'Выберите аватар', 'avatar.button': 'Продолжить',
    'profile.subscription': 'Подписка', 'profile.active': 'Активна', 'profile.expired': 'Истекла',
    'profile.renew': 'Продлить', 'profile.plans': 'Тарифы', 'profile.server': 'Сервер',
    'profile.status': 'Статус', 'profile.remaining': 'Осталось', 'profile.unlimited': 'Безлимит',
    'profile.live_status': 'ТВ', 'profile.open': 'Открыт', 'profile.closed': 'Закрыт',
    'live.all': 'Все', 'live.search': 'Поиск...', 'live.no_channels': 'Каналы не найдены',
    'common.loading': 'Загрузка...', 'common.error': 'Ошибка', 'common.retry': 'Повторить',
    'footer.rights': 'Все права защищены.',
    'premium.badge': 'Выберите тариф', 'premium.title': 'Цены', 'premium.subtitle': 'Выберите план',
    'premium.monthly': '1 месяц', 'premium.monthly.dur': '30 дней', 'premium.quarterly': '3 месяца',
    'premium.quarterly.dur': '90 дней', 'premium.yearly': '12 месяцев', 'premium.yearly.dur': '365 дней',
    'premium.buy': 'Купить', 'premium.popular': 'Популярный',
  },
  uk: {
    'nav.home': 'Головна', 'nav.live': 'ТВ', 'nav.movies': 'Фільми', 'nav.series': 'Серіали',
    'nav.profile': 'Профіль', 'nav.logout': 'Вийти', 'nav.search': 'Пошук',
    'hero.play': 'Дивитись', 'hero.detail': 'Деталі',
    'content.featured': 'Рекомендоване', 'content.popular': 'Популярне', 'content.recent': 'Новинки',
    'content.similar': 'Схожі', 'content.categories': 'Категорії', 'content.no_content': 'Контент не знайдено',
    'content.seasons': 'Сезони', 'content.episodes': 'Серії', 'content.cast': 'Актори',
    'content.director': 'Режисер', 'content.genre': 'Жанр', 'content.release': 'Рік', 'content.rating': 'Рейтинг',
    'content.duration': 'Тривалість', 'content.trailer': 'Трейлер',
    'player.play': 'Грати', 'player.pause': 'Пауза', 'player.buffering': 'Завантаження...',
    'player.mute': 'Без звуку', 'player.unmute': 'Звук', 'player.fullscreen': 'На весь екран',
    'player.settings': 'Налаштування', 'player.speed': 'Швидкість', 'player.live': 'LIVE',
    'login.title': 'Вхід', 'login.username': "Ім'я", 'login.password': 'Пароль',
    'login.button': 'Увійти', 'login.error': "Невірне ім'я або пароль",
    'login.loading': 'Вхід...', 'login.remember': "Запам'ятати",
    'avatar.title': 'Виберіть аватар', 'avatar.button': 'Продовжити',
    'profile.subscription': 'Підписка', 'profile.active': 'Активна', 'profile.expired': 'Закінчилась',
    'profile.renew': 'Продовжити', 'profile.plans': 'Тарифи', 'profile.server': 'Сервер',
    'profile.status': 'Статус', 'profile.remaining': 'Залишилось', 'profile.unlimited': 'Безліміт',
    'profile.live_status': 'ТВ', 'profile.open': 'Відкрито', 'profile.closed': 'Закрито',
    'live.all': 'Всі', 'live.search': 'Пошук...', 'live.no_channels': 'Канали не знайдено',
    'common.loading': 'Завантаження...', 'common.error': 'Помилка', 'common.retry': 'Повторити',
    'footer.rights': 'Всі права захищені.',
  },
  de: {
    'nav.home': 'Startseite', 'nav.live': 'Live TV', 'nav.movies': 'Filme', 'nav.series': 'Serien',
    'nav.profile': 'Profil', 'nav.logout': 'Abmelden', 'nav.search': 'Suche',
    'hero.play': 'Abspielen', 'hero.detail': 'Details',
    'content.featured': 'Empfohlen', 'content.popular': 'Beliebt', 'content.recent': 'Neu',
    'content.similar': 'Ähnliche', 'content.categories': 'Kategorien', 'content.no_content': 'Kein Inhalt',
    'content.seasons': 'Staffeln', 'content.episodes': 'Episoden', 'content.cast': 'Besetzung',
    'content.director': 'Regisseur', 'content.genre': 'Genre', 'content.release': 'Jahr', 'content.rating': 'Bewertung',
    'content.duration': 'Dauer', 'content.trailer': 'Trailer',
    'player.play': 'Play', 'player.pause': 'Pause', 'player.buffering': 'Lädt...',
    'player.mute': 'Stumm', 'player.unmute': 'Laut', 'player.fullscreen': 'Vollbild',
    'player.settings': 'Einstellungen', 'player.speed': 'Geschwindigkeit', 'player.live': 'LIVE',
    'login.title': 'Anmelden', 'login.username': 'Benutzername', 'login.password': 'Passwort',
    'login.button': 'Einloggen', 'login.error': 'Falscher Benutzername oder Passwort',
    'login.loading': 'Einloggen...', 'login.remember': 'Erinnern',
    'avatar.title': 'Avatar wählen', 'avatar.button': 'Weiter',
    'profile.subscription': 'Abonnement', 'profile.active': 'Aktiv', 'profile.expired': 'Abgelaufen',
    'profile.renew': 'Verlängern', 'profile.plans': 'Tarife', 'profile.server': 'Server',
    'profile.status': 'Status', 'profile.remaining': 'Übrig', 'profile.unlimited': 'Unbegrenzt',
    'profile.live_status': 'Live TV', 'profile.open': 'Offen', 'profile.closed': 'Geschlossen',
    'live.all': 'Alle', 'live.search': 'Sender suchen...', 'live.no_channels': 'Keine Sender',
    'common.loading': 'Laden...', 'common.error': 'Fehler', 'common.retry': 'Wiederholen',
    'footer.rights': 'Alle Rechte vorbehalten.',
  },
  fr: {
    'nav.home': 'Accueil', 'nav.live': 'TV Live', 'nav.movies': 'Films', 'nav.series': 'Séries',
    'nav.profile': 'Profil', 'nav.logout': 'Déconnexion', 'nav.search': 'Recherche',
    'hero.play': 'Regarder', 'hero.detail': 'Détails',
    'content.featured': 'Recommandé', 'content.popular': 'Populaire', 'content.recent': 'Nouveautés',
    'content.similar': 'Similaire', 'content.categories': 'Catégories', 'content.no_content': 'Aucun contenu',
    'content.seasons': 'Saisons', 'content.episodes': 'Épisodes', 'content.cast': 'Acteurs',
    'content.director': 'Réalisateur', 'content.genre': 'Genre', 'content.release': 'Année', 'content.rating': 'Note',
    'content.duration': 'Durée', 'content.trailer': 'Bande-annonce',
    'player.play': 'Lecture', 'player.pause': 'Pause', 'player.buffering': 'Chargement...',
    'player.mute': 'Silencieux', 'player.unmute': 'Son', 'player.fullscreen': 'Plein écran',
    'player.settings': 'Paramètres', 'player.speed': 'Vitesse', 'player.live': 'LIVE',
    'login.title': 'Connexion', 'login.username': 'Utilisateur', 'login.password': 'Mot de passe',
    'login.button': 'Se connecter', 'login.error': 'Identifiant incorrect',
    'login.loading': 'Connexion...', 'login.remember': 'Se souvenir',
    'avatar.title': 'Choisir avatar', 'avatar.button': 'Continuer',
    'profile.subscription': 'Abonnement', 'profile.active': 'Actif', 'profile.expired': 'Expiré',
    'profile.renew': 'Renouveler', 'profile.plans': 'Forfaits', 'profile.server': 'Serveur',
    'profile.status': 'Statut', 'profile.remaining': 'Restant', 'profile.unlimited': 'Illimité',
    'profile.live_status': 'TV Live', 'profile.open': 'Ouvert', 'profile.closed': 'Fermé',
    'live.all': 'Tout', 'live.search': 'Rechercher...', 'live.no_channels': 'Aucune chaîne',
    'common.loading': 'Chargement...', 'common.error': 'Erreur', 'common.retry': 'Réessayer',
    'footer.rights': 'Tous droits réservés.',
  },
  it: {
    'nav.home': 'Home', 'nav.live': 'TV Live', 'nav.movies': 'Film', 'nav.series': 'Serie',
    'nav.profile': 'Profilo', 'nav.logout': 'Esci', 'nav.search': 'Cerca',
    'hero.play': 'Guarda', 'hero.detail': 'Dettagli',
    'content.featured': 'In evidenza', 'content.popular': 'Popolare', 'content.recent': 'Novità',
    'content.similar': 'Simili', 'content.categories': 'Categorie', 'content.no_content': 'Nessun contenuto',
    'content.seasons': 'Stagioni', 'content.episodes': 'Episodi', 'content.cast': 'Cast',
    'content.director': 'Regista', 'content.genre': 'Genere', 'content.release': 'Anno', 'content.rating': 'Valutazione',
    'content.duration': 'Durata', 'content.trailer': 'Trailer',
    'player.play': 'Play', 'player.pause': 'Pausa', 'player.buffering': 'Caricamento...',
    'player.mute': 'Muto', 'player.unmute': 'Suono', 'player.fullscreen': 'Schermo intero',
    'player.settings': 'Impostazioni', 'player.speed': 'Velocità', 'player.live': 'LIVE',
    'login.title': 'Accedi', 'login.username': 'Nome utente', 'login.password': 'Password',
    'login.button': 'Accedi', 'login.error': 'Nome utente o password errati',
    'login.loading': 'Accesso...', 'login.remember': 'Ricordami',
    'avatar.title': 'Scegli avatar', 'avatar.button': 'Continua',
    'profile.subscription': 'Abbonamento', 'profile.active': 'Attivo', 'profile.expired': 'Scaduto',
    'profile.renew': 'Rinnova', 'profile.plans': 'Piani', 'profile.server': 'Server',
    'profile.status': 'Stato', 'profile.remaining': 'Rimanente', 'profile.unlimited': 'Illimitato',
    'profile.live_status': 'TV Live', 'profile.open': 'Aperto', 'profile.closed': 'Chiuso',
    'live.all': 'Tutti', 'live.search': 'Cerca canale...', 'live.no_channels': 'Nessun canale',
    'common.loading': 'Caricamento...', 'common.error': 'Errore', 'common.retry': 'Riprova',
    'footer.rights': 'Tutti i diritti riservati.',
  },
}

const langNames: Record<string, string> = {
  tr: 'Türkçe', en: 'English', ru: 'Русский', uk: 'Українська', de: 'Deutsch', fr: 'Français', it: 'Italiano',
}

const LangContext = createContext<any>(null)

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState(() => { try { return localStorage.getItem('lang') || 'tr' } catch { return 'tr' } })
  const setLang = (l: string) => { setLangState(l); try { localStorage.setItem('lang', l) } catch {}; document.documentElement.lang = l }
  useEffect(() => { document.documentElement.lang = lang }, [lang])
  const t = (key: string) => data[lang]?.[key] ?? data['tr']?.[key] ?? key
  return <LangContext.Provider value={{ lang, setLang, t, langNames, languages: Object.keys(data) }}>{children}</LangContext.Provider>
}

export function useLang() {
  return useContext(LangContext)
}
